### ISSUE TITLE
Allow custom categories

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-resources#103]
### Subject of the enhancement
I would like to explore how to implement custom categories via JSON config only. We have clients that use categories other than the default document, media, and link.

### Considerations

- How would the schemas be affected? Would AAT users be able to add as many categories as they need?
- If there are a large number of categories, the drawer width may need to be wider.
- Should we just add x amount of generic categories, and course editors / developers can update these as needed? Maybe the ability for up to 10-15 custom categories?
- Backwards compatibility
- Should we use a new flexible structure for the categories in the JSON?

**Current:**
```
  "_resources": {
    "_isEnabled": true,
    "_filterButtons": {
      "all": "All",
      "document": "Document",
      "media": "Media",
      "link": "Link"
    },
    "_filterAria": {
      "allAria": "View all resources",
      "documentAria": "View document resources",
      "mediaAria": "View media resources",
      "linkAria": "View resource links"
    },
```

**Alternative example:**
```
  "_resources": {
    "_isEnabled": true,
    "_resourcesTypes": [
      {
        "buttonText": "All",
        "ariaLabel": "View all resources",
        "_type": "all"
      },
      {
        "buttonText": "Media",
        "ariaLabel": "View media resources",
        "_type": "media"
      },
      {
        "buttonText": "Document",
        "ariaLabel": "View document resources",
        "_type": "document"
      },
      {
        "buttonText": "Link",
        "ariaLabel": "View resource links",
        "_type": "link"
      }
    ],
```

**Comment by oliverfoster** [comment]
I don't think you'll want two independent lists, on for items and one for types. Primarily as you need to refer to the types list from the items list.

It may he better to nest them in the schema, such that each type can have many items, assuming that nested lists is something the AAT can handle. "All" items is then a concatenation of all type items and items type IDs never need to be manually created or referenced.

```js
[
  {
    "typeName": "Media",
    "_items": [
      {
        "title": "YouTube video of...",
        "_src": "https://m.youtube.com/watch?v=xvFZjo5PgG0
      }
    ]
  },
  {
    "typeName": "Documents",
    "_items": [
      {
        "title": "YouTube video of...",
        "_src": "https://m.youtube.com/watch?v=xvFZjo5PgG0
      }
    ]
  }
]

```

**Comment by swashbuck** [comment]
> I don't think you'll want two independent lists, one for items and one for types. Primarily as you need to refer to the types list from the items list.
> 
> It may be better to nest them in the schema, such that each type can have many items, assuming that nested lists is something the AAT can handle. "All" items is then a concatenation of all type items and items type IDs never need to be manually created or referenced.

@taylortom @joe-allen-89 Do you see any potential AAT issues with Ollie's approach above?

**Comment by taylortom** [comment]
Unfortunately neither the legacy or v1 AAT UIs support nested lists right now (although it is something that's been asked for previously)

**Comment by oliverfoster** [comment]
Changing the schema this violently may be a concern for updates to existing courses.

**Comment by swashbuck** [comment]
My other idea was less elegant, but it shouldn't affect current courses. Just hardcoding a bunch of custom categories.

```
  "_resources": {
    "_isEnabled": true,
    "_filterButtons": {
      "all": "All",
      "document": "Document",
      "media": "Media",
      "link": "Link",
      "custom1": "Custom category 1",
      "custom2": "Custom category 2",
      "custom3": "Custom category 3",
      "custom4": "Custom category 4",
      "custom5": "Custom category 5",
    },
    "_filterAria": {
      "allAria": "View all resources",
      "documentAria": "View document resources",
      "mediaAria": "View media resources",
      "linkAria": "View resource links"
      "custom1Aria": "View custom category 1 links",
      "custom2Aria": "View custom category 2 links",
      "custom3Aria": "View custom category 3 links",
      "custom4Aria": "View custom category 4 links",
      "custom5Aria": "View custom category 5 links",
    },
```

**Comment by oliverfoster** [comment]
Where are the resource types filtered based on >= 1 items? I can't see it.

**Comment by swashbuck** [comment]
@oliverfoster I believe you're looking for resourcesHasType() in resourcesFilterButton.jsx?

**Comment by oliverfoster** [comment]
@swashbuck example.json and readme.md

**Comment by swashbuck** [comment]
> @swashbuck example.json and readme.md

example.json should be good, but readme needs to be updated.
