### ISSUE TITLE
End to end tests are needed for the resources extension

### ISSUE THREAD

**Issue by lemmyadams** [adaptlearning/adapt-contrib-resources#111]
### Subject of the issue/enhancement/features
Now that e2e tests are run on PR creation we should add to these. This issue is specifically directed at tests for the resources to appear in the drawer extension

### Your environment
* >= [v5.30.0](https://github.com/adaptlearning/adapt_framework/releases/tag/v5.30.0)

**Comment by oliverfoster** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-resources/pull/112
