### ISSUE TITLE
Where do I add language and language constants?

### ISSUE THREAD

**Issue by alexkash** [adaptlearning/adapt-contrib-resources#86]
### Subject of the issue/enhancement/features
Hi!
I want to translate the interface into Ukrainian and do not understand how to do it. I'm not a programmer, but I can edit the translation file. :) Please help me.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by oliverfoster** [comment]
Please post in only one place.
https://github.com/adaptlearning/adapt-contrib-assessment/issues/177
